version: '3.7'
services:
    db:
        image: mysql:8
        container_name: bct-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: ['--skip-log-bin', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
        volumes:
            - bct-database:/var/lib/mysql
            - ./database-schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        networks:
            - bct-net
            
    dbadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bct-dbadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 1000000000
        ports:
            - '${PUBLIC_PHPMYADMIN_PORT}:80'
        depends_on:
            - db
        networks:
            - bct-net

    api:
        build: ./api
        restart: unless-stopped
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            ONION_EXPLORER_HOST: ${ONION_EXPLORER_HOST}
        ports:
            - "${API_PORT}:3001"
        depends_on:
            - db
        networks:
            - bct-net

    frontend:
        build: ./frontend
        restart: unless-stopped
        command: >
            sh -c '
                #echo "Starting site in production mode...";
                #yarn serve;
                echo "Starting site in development mode...";
                yarn start
            '
        ports:
            - "${FRONTEND_PORT}:3000"
        depends_on:
            - db
        networks:
            - bct-net

volumes:
    bct-database:

networks:
    bct-net:
        name: bct-net
        driver: bridge
